#ifndef _IOHANDLERTYPE_H
#define	_IOHANDLERTYPE_H

typedef enum _IOHandlerType {
	IOHT_ACCEPTOR,
	IOHT_TCP_CONNECTOR,
	IOHT_TCP_CARRIER,
	IOHT_UDP_CARRIER,
	IOHT_INBOUNDNAMEDPIPE_CARRIER,
	IOHT_TIMER,
	IOHT_STDIO
} IOHandlerType;

#endif
