// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.


// This file is autogenerated by
//     base/android/jni_generator/jni_generator.py
// For
//     org/webrtc/CodecsWrapperTestHelper

#ifndef org_webrtc_CodecsWrapperTestHelper_JNI
#define org_webrtc_CodecsWrapperTestHelper_JNI

#include <jni.h>

#include "sdk/android/src/jni/jni_generator_helper.h"


// Step 1: Forward declarations.

JNI_REGISTRATION_EXPORT extern const char kClassPath_org_webrtc_CodecsWrapperTestHelper[];
const char kClassPath_org_webrtc_CodecsWrapperTestHelper[] = "org/webrtc/CodecsWrapperTestHelper";
// Leaking this jclass as we cannot use LazyInstance from some threads.
JNI_REGISTRATION_EXPORT base::subtle::AtomicWord g_org_webrtc_CodecsWrapperTestHelper_clazz = 0;
#ifndef org_webrtc_CodecsWrapperTestHelper_clazz_defined
#define org_webrtc_CodecsWrapperTestHelper_clazz_defined
inline jclass org_webrtc_CodecsWrapperTestHelper_clazz(JNIEnv* env) {
  return base::android::LazyGetClass(env, kClassPath_org_webrtc_CodecsWrapperTestHelper,
      &g_org_webrtc_CodecsWrapperTestHelper_clazz);
}
#endif


// Step 2: Constants (optional).


// Step 3: Method stubs.
namespace  webrtc {
namespace jni {


static base::subtle::AtomicWord g_org_webrtc_CodecsWrapperTestHelper_createTestVideoCodecInfo = 0;
static base::android::ScopedJavaLocalRef<jobject>
    Java_CodecsWrapperTestHelper_createTestVideoCodecInfo(JNIEnv* env) {
  CHECK_CLAZZ(env, org_webrtc_CodecsWrapperTestHelper_clazz(env),
      org_webrtc_CodecsWrapperTestHelper_clazz(env), NULL);
  jmethodID method_id = base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_STATIC>(
          env, org_webrtc_CodecsWrapperTestHelper_clazz(env),
          "createTestVideoCodecInfo",
          "()Lorg/webrtc/VideoCodecInfo;",
          &g_org_webrtc_CodecsWrapperTestHelper_createTestVideoCodecInfo);

  jobject ret =
      env->CallStaticObjectMethod(org_webrtc_CodecsWrapperTestHelper_clazz(env),
          method_id);
  jni_generator::CheckException(env);
  return base::android::ScopedJavaLocalRef<jobject>(env, ret);
}

}  // namespace jni
}  // namespace  webrtc

#endif  // org_webrtc_CodecsWrapperTestHelper_JNI
